/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DBtest;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class AppTest {
  @Test public void appHasAGreeting() {
    AppTest classUnderTest = new AppTest();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
